#apiVersion: batch/v1
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: throw-dice-cron-job
spec:
  schedule: "30 21 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: throw-dice
            image: kodekloud/throw-dice
          # restartPolicy: OnFailure
          restartPolicy: Never
      completions: 3
      parallelism: 3